apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: target.c3.docker.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: c3.docker.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                context:
                  type: string
                image:
                  type: string
                cmd:
                  type: integer
                registry:
                  type: string
                registryUser:
                  type: string
                ingress:
                  type: string
                replicas:
                  type: integer
                storageClass:
                  type: string
                useHPA:
                  type: boolean
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: targets
    # singular name to be used as an alias on the CLI and for display
    singular: target
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Default
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - tg