apiVersion: v1
kind: ServiceAccount
metadata:
  name: c3-admin
  namespace: c3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: c3-cr
rules:
# Allow to get, list and watch namespaces
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Allow to get, list and watch customresourcedefinitions
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: c3-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: c3-cr
subjects:
- kind: ServiceAccount
  name: c3-admin
  namespace: c3