apiVersion: v1
kind: ServiceAccount
metadata:
  name: c3
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: c3-admin
  namespace: default
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c3-admin
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: c3-admin
subjects:
  - kind: ServiceAccount
    name: c3
    namespace: default